### ISSUE TITLE
Question about failing libcmaes Installation through BSMPT Cmake

### ISSUE THREAD

**Issue by phbasler** [PhaseTracer/PhaseTracer#10]
Dear all, 

In your new Readme you write 
"We have found that the libmaes package often needs to be installed manually as BSMPT's cmake system often fails to install this."
Can you tell me what you mean with this? And does it still occur with the 2.0.1 Release?

Cheers
Philipp

**Comment by phyzhangyang** [comment]
Hi Philipp,

When I installed BSMPT on Mac using "CMAES_ROOT=./libcmaes cmake ..", I met the following error,

-- libCMAES not found, downloading...
Preparing the libcmaes build system...please wait

Found GNU Autoconf version 2.65
Found GNU Automake version 1.15.1
Found GNU Libtool version 2.4.6

Automatically preparing build ... Warning: autoreconf failed
Attempting to run the preparation steps individually

Preparing build ... ERROR: aclocal failed
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for `install'.
CMake Error at /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CMAES (missing: CMAES_LIBRARY)

But I can install standalone libcmaes successfully. Thus we didn't specify CMAES_ROOT in PhaseTracer cmake, so that it can find the libcmaes in /usr/local/lib. Then users meet the following error:

[100%] Built target lcmaes
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: /usr/local/include/libcmaes.  Maybe need
  administrative privileges.

In BSMPT2, libcmaes is optional. As we only use the potential in BSMPT, there may be no such problem.

I was planning to ask you about this. I'm sorry that I forgot to send the email. 

Best,
Yang

**Comment by phbasler** [comment]
Hi Yang, 

No problem.
I asked our Mac User and his suggestion was that you do not have installed autotools. 
Once you install it through `brew install autoconf automake` you should be fine. 

Please tell me if it worked.

I don't have the time at the moment, but at some point this month I will add an dependecy list for libcmaes to our Readme, this should prevent problems like this.

**Comment by phyzhangyang** [comment]
Hi Philipp,

Thanks for the suggestion. My autoconf is broken after I upgraded my system recently. 

After fixing autoconf, I met another error which is caused by using relative path for CMAES_ROOT. I have to use absolute path for CMAES_ROOT. 

Then I met an error:

configure: libcmaes 0.9.5
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin19.6.0
checking host system type... x86_64-apple-darwin19.6.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/zhangyang/Downloads/BSMPT-1.1.2/build/libcmaes-0.9.5':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for `install'.
CMake Error at /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CMAES (missing: CMAES_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  tools/cmake/FindCMAES.cmake:66 (find_package_handle_standard_args)
  CMakeLists.txt:15 (find_package) 

Do you have any idea how to solve it?

Best, Yang

**Comment by phbasler** [comment]
Hi Yang, 

This looks like some miscommunication in the cmake file. I just noticed today that libcmaes had a new release in May (after 5 years) where they now provide a cmake installation. We will update BMSPT to use this and then this should work better.

**Comment by phyzhangyang** [comment]
I will update the BSMPT used in PhaseTracer to v2.

**Comment by phyzhangyang** [comment]
We have upgraded BSMPT used in PhaseTracer to v2.1, in which we do not require libcmaes, because we only use potential functions of BSMPT.
